version: '3.8'

services:
  mais-git-runner:
    image: mais-git-runner:latest
    container_name: mais-git-runner
    environment:
      - RUNNER_NAME=GIT-RUNNER
      - REPO_URL=https://github.com/your_user/your_repo
      - RUNNER_TOKEN=your_token
      - RUNNER_WORKDIR=/tmp/runner_work
