version: '3.8'

services:
  github-runner:
    image: mais-git-runner:latest
    container_name: mais-git-runner
    environment:
      - RUNNER_NAME="runner-default"
      - REPO_URL=""
      - RUNNER_TOKEN=""
      - RUNNER_WORKDIR=/tmp/runner_work
    restart: no